-- Generated by db/exportSeed.ts from src/data/applications.ts. Do not edit by hand.
-- Regenerate with: npm run db:seed-sql

insert into applications (
  id, name, description, url, icon, category, status, favorite, color,
  last_opened, requires_auth, auth_provider, launch_type, auth, roles,
  permissions, sort_order
) values
  ('hris', 'HRIS', 'Employee data, payroll and leave management', 'https://hris.maharasa.id', 'Users', 'Human Resource', 'online', true, '#0F9D58', null, false, null, 'new_tab', null, null, null, 0),
  ('helpdesk', 'IT Helpdesk', 'IT ticket management and support requests', 'https://helpdesk.maharasa.id/auth/login', 'LifeBuoy', 'IT', 'offline', true, '#1976D2', null, false, null, 'new_tab', null, null, null, 1),
  ('tukar-faktur', 'Tukar Faktur Online', 'Online invoice exchange scheduling for vendors', 'https://tukarfaktur.maharasa.id', 'ReceiptText', 'Finance', 'online', true, '#00897B', null, false, null, 'new_tab', null, null, null, 2),
  ('cmms', 'CMMS', 'Maintenance planning and work order tracking', 'https://helpdesk.maharasa.id/auth/login', 'Wrench', 'Production', 'online', false, '#F4511E', null, false, null, 'new_tab', null, null, null, 3),
  ('inventory', 'Inventory', 'Stock levels, movements and warehouse balances', 'https://inventory.maharasa.id', 'Boxes', 'Warehouse', 'offline', false, '#5E35B1', null, false, null, 'new_tab', null, null, null, 4),
  ('purchase', 'Purchase', 'Purchase requests, orders and vendor quotations', 'https://purchase.maharasa.id', 'ShoppingCart', 'Operations', 'offline', false, '#3949AB', null, false, null, 'new_tab', null, null, null, 5),
  ('sales-dashboard', 'Sales Dashboard', 'Revenue, targets and channel performance', 'https://sales.maharasa.id', 'TrendingUp', 'Sales', 'offline', false, '#00ACC1', null, false, null, 'new_tab', null, null, null, 6),
  ('recruitment', 'Recruitment', 'Job openings, candidates and interview pipeline', 'https://recruitment.maharasa.id', 'UserPlus', 'Human Resource', 'offline', false, '#7CB342', null, false, null, 'new_tab', null, null, null, 7),
  ('asset-management', 'Asset Management', 'Company asset registry, custody and depreciation', 'https://asset.maharasa.id', 'Package', 'Administration', 'offline', false, '#6D4C41', null, false, null, 'new_tab', null, null, null, 8),
  ('vendor-portal', 'Vendor Portal', 'Supplier registration, contracts and documents', 'https://vendor.maharasa.id', 'Handshake', 'Operations', 'offline', false, '#8E24AA', null, false, null, 'new_tab', null, null, null, 9),
  ('approval', 'Approval System', 'Multi-level document and request approvals', 'https://approval.maharasa.id', 'CircleCheckBig', 'Management', 'offline', false, '#2E7D32', null, false, null, 'new_tab', null, null, null, 10),
  ('colorplate', 'Colorplate Production', 'Printing plate production scheduling and QC', 'https://maharasa.calira.my.id/login', 'Palette', 'Production', 'online', false, '#D81B60', null, false, null, 'new_tab', null, null, null, 11),
  ('attendance', 'Fingerprint Machine', 'Fingerprint and attendance monitoring', 'https://finger.maharasa.id', 'ScanFace', 'Human Resource', 'online', false, '#43A047', null, false, null, 'new_tab', null, null, null, 12),
  ('dms', 'Document Management', 'Company document archive and version control', 'https://dms.maharasa.id', 'FolderOpen', 'Administration', 'offline', false, '#546E7A', null, false, null, 'new_tab', null, null, null, 13),
  ('customer-feedback', 'Customer Feedback', 'Survey responses and customer satisfaction index', 'https://feedback.maharasa.id', 'MessageSquareHeart', 'Sales', 'offline', false, '#C2185B', null, false, null, 'new_tab', null, null, null, 14),
  ('payroll', 'Payroll Center', 'Salary runs, THR and payslip distribution', 'https://eslip.maharasa.id/', 'Wallet', 'Human Resource', 'online', false, '#00838F', null, false, null, 'new_tab', null, null, null, 15),
  ('fleet', 'Fleet Management', 'Vehicle usage, service history and fuel logs', 'https://fleet.maharasa.id', 'Truck', 'Operations', 'offline', false, '#455A64', null, false, null, 'new_tab', null, null, null, 16),
  ('qms', 'Quality Management', 'Inspection results, NCR and corrective actions', 'https://qms.maharasa.id', 'ShieldCheck', 'Production', 'offline', false, '#1E88E5', null, false, null, 'new_tab', null, null, null, 17),
  ('learning', 'Learning Center', 'Internal training modules and certifications', 'https://learning.maharasa.id', 'GraduationCap', 'Human Resource', 'offline', false, '#8D6E63', null, false, null, 'new_tab', null, null, null, 18),
  ('meeting-room', 'Meeting Room Booking', 'Reserve meeting rooms and shared facilities', 'https://rooms.maharasa.id', 'CalendarDays', 'Administration', 'offline', false, '#7E57C2', null, false, null, 'new_tab', null, null, null, 19),
  ('it-inventory', 'IT Asset Inventory', 'Laptops, licenses and hardware assignment', 'https://itasset.maharasa.id', 'Laptop', 'IT', 'offline', false, '#039BE5', null, false, null, 'new_tab', null, null, null, 20),
  ('monitoring', 'Infrastructure Monitoring', 'Server, network and uptime observability', 'https://monitoring.maharasa.id', 'Activity', 'IT', 'offline', false, '#00BFA5', null, false, null, 'new_tab', null, null, null, 21)
on conflict (id) do nothing;
