/**
 * Generates the initial data load from the seed catalogue.
 *
 * Writes `db/002_seed.sql` so the SQL never drifts from the file it came from:
 *
 *   npm run db:seed-sql
 *
 * It writes the file itself rather than printing to stdout, because a shell
 * redirect would capture npm's own banner lines into the SQL.
 *
 * Every entry in `APPLICATIONS` is emitted with the status it carries there,
 * so an application parked as `offline` loads as `offline`.
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { APPLICATIONS } from "../src/data/applications";

const quote = (value: string): string => `'${value.replace(/'/g, "''")}'`;
const nullable = (value: string | null | undefined): string =>
  value === null || value === undefined ? "null" : quote(value);
const json = (value: unknown): string =>
  value === undefined || value === null ? "null" : `${quote(JSON.stringify(value))}::jsonb`;

const rows = APPLICATIONS.map((app, index) =>
  [
    quote(app.id),
    quote(app.name),
    quote(app.description),
    quote(app.url),
    quote(app.icon),
    quote(app.category),
    quote(app.status),
    String(app.favorite),
    quote(app.color),
    nullable(app.lastOpened),
    String(app.requiresAuth),
    nullable(app.authProvider),
    quote(app.launchType),
    json(app.auth),
    json(app.roles),
    json(app.permissions),
    String(index),
  ].join(", "),
);

const sql =
  `-- Generated by db/exportSeed.ts from src/data/applications.ts. Do not edit by hand.\n` +
  `-- Regenerate with: npm run db:seed-sql\n\n` +
  `insert into applications (\n` +
  `  id, name, description, url, icon, category, status, favorite, color,\n` +
  `  last_opened, requires_auth, auth_provider, launch_type, auth, roles,\n` +
  `  permissions, sort_order\n` +
  `) values\n` +
  rows.map((row) => `  (${row})`).join(",\n") +
  `\non conflict (id) do nothing;\n`;

const target = join(dirname(fileURLToPath(import.meta.url)), "002_seed.sql");
writeFileSync(target, sql, "utf8");
process.stdout.write(`Wrote ${APPLICATIONS.length} applications to ${target}\n`);
